PYTHON = python3
SCRIPT = LAB4_Kripper_Gonzalez.py 
OUTPUTS = aislamiento.txt diagnostico_final.txt ronda_*.txt acciones_anticuerpo.txt

run: $(SCRIPT)
	@$(PYTHON) $(SCRIPT)

clean:
	@rm -f $(OUTPUTS)
